# Generated by Django 4.1.3 on 2023-01-08 19:08

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='profiles', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='core.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='avatars', verbose_name='Profile Icon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='core.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='show',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='core.uploadedimage'),
        ),
    ]
